command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

resources:
  my_secret:
  type: secret
  key: dbx-samir-prem-token
  scope: atlas-scopes

env:
  - name: "SERVING_ENDPOINT_NAME"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "LOCAL_API_TOKEN"
    valueFrom: my_secret_test
  - name: "DATABRICKS_HOST"
    value: "https://adb-2148269122003508.8.azuredatabricks.net/"