command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

env:
  - name: "SERVING_ENDPOINT_NAME"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "LOCAL_API_TOKEN"
    valueFrom: "{{secrets/atlas-scopes/dbx-samir-prem-token}}"
  - name: "DATABRICKS_HOST"
    value: "https://adb-2148269122003508.8.azuredatabricks.net/"